name: Dagger CI

on:
    workflow_dispatch:
    #push:
    #    branches: [main]
    #pull_request:
    #    branches: [main]

jobs:
    test:
        name: Run Tests
        runs-on: rcc-runner-k8s
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Dagger Pipeline
              uses: dagger/dagger-for-github@v7
              with:
                  verb: call
                  args: test --source .
                  version: "latest"
